/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/queue-admin/retry-dlq/{dlqName}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['retryDlq']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/queue-admin/retry-all-dlqs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['retryAllDlqs']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/queue-admin/purge-queue/{queueName}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations['purgeQueue']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/legacy/adjustments/{adjustmentId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get an adjustments
     * @description Get details of an adjustment in the NOMIS system format.
     */
    get: operations['get']
    /**
     * Update an adjustments
     * @description Synchronise an update from NOMIS into adjustments API.
     */
    put: operations['update']
    post?: never
    /**
     * Delete an adjustments
     * @description Synchronise a deletion from NOMIS into adjustments API.
     */
    delete: operations['delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/adjustments/{adjustmentId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get an adjustments
     * @description Get details of an adjustment
     */
    get: operations['get_1']
    /**
     * Update an adjustments
     * @description Update an adjustment.
     */
    put: operations['update_1']
    post?: never
    /**
     * Delete an adjustments
     * @description Delete an adjustment.
     */
    delete: operations['delete_1']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/legacy/adjustments': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create an adjustments
     * @description Synchronise a creation from NOMIS into adjustments API.
     */
    post: operations['create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/legacy/adjustments/migration': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create an adjustment from the migration job
     * @description Synchronise a creation from NOMIS into adjustments API. This endpoint is used for initial migration of data from NOMIS without raising any events.
     */
    post: operations['migration']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/adjustments': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get current adjustments by person
     * @description Get current adjustments for a given person.
     */
    get: operations['findByPerson']
    put?: never
    /**
     * Create adjustments
     * @description Create adjustment.
     */
    post: operations['create_1']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/adjustments/{adjustmentId}/effective-days': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Update the effective calculable days for and adjustment
     * @description Update an adjustment's effective days.
     */
    post: operations['updateEffectiveDays']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/adjustments/validate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Validate an adjustments
     * @description Validate an adjustment.
     */
    post: operations['validate']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/adjustments/restore': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Restore a deleted adjustment
     * @description Restore a deleted adjustment
     */
    post: operations['restore']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/adjustments/person/{person}/manual-unused-deductions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Update the unused deduction days for a person
     * @description Update the unused deduction days for a person
     */
    post: operations['setUnusedDaysManually']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/adjustments/additional-days/{person}/reject-prospective-ada': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Reject prospective ADA. */
    post: operations['rejectProspectiveAda']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/legacy/adjustments/{adjustmentId}/current-term': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * Set the current term of an adjustment
     * @description Temporary endpoint to migrate the current term value of an adjustment.
     */
    patch: operations['setCurrentTerm']
    trace?: never
  }
  '/things-to-do/prisoner/{prisonerId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Retrieve things-to-do for a prisoner
     * @description Provides a list of things-to-do for a specified prisoner based on their ID.
     */
    get: operations['getThingsToDo']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/queue-admin/get-dlq-messages/{dlqName}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getDlqMessages']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/adjustments/person/{person}/unused-deductions-result': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get the unused deductions result
     * @description Get the unused deductions result
     */
    get: operations['getUnusedDeductionsResult']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/adjustments/additional-days/{person}/adjudication-details': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get all details of adjudications and associated adjustments */
    get: operations['getAdaAdjudicationDetails']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    RetryDlqResult: {
      /** Format: int32 */
      messagesFoundCount: number
    }
    PurgeQueueResult: {
      /** Format: int32 */
      messagesFoundCount: number
    }
    /** @description An adjustment structured for synchronising with the NOMIS system */
    LegacyAdjustment: {
      /**
       * Format: int64
       * @description The NOMIS booking ID of the adjustment
       */
      bookingId: number
      /**
       * Format: int32
       * @description The NOMIS sentence sequence of the adjustment
       */
      sentenceSequence?: number
      /** @description The NOMIS offender number aka nomsId, prisonerId of the person this adjustment applies to */
      offenderNo: string
      /**
       * @description The NOMIS adjustment type
       * @enum {string}
       */
      adjustmentType: 'ADA' | 'RADA' | 'UAL' | 'LAL' | 'SREM' | 'RSR' | 'RST' | 'RX' | 'S240A' | 'UR' | 'TCA' | 'TSA'
      /**
       * Format: date
       * @description The NOMIS date of adjustment
       */
      adjustmentDate?: string
      /**
       * Format: date
       * @description The NOMIS from date of adjustment
       */
      adjustmentFromDate?: string
      /**
       * Format: int32
       * @description The NOMIS adjustment days
       */
      adjustmentDays: number
      /** @description The NOMIS comment for this adjustment */
      comment?: string
      /** @description The NOMIS active or inactive flag */
      active: boolean
      /** @description Has the prisoner been released from the NOMIS booking */
      bookingReleased: boolean
      /** @description The ID of the agency the prisoner is located */
      agencyId?: string
      /** @description Is the adjustment part of the current term. (Most recent booking NOMIS) */
      currentTerm: boolean
    }
    /** @description The details of an additional days awarded (ADA) adjustment */
    AdditionalDaysAwardedDto: {
      /** @description The id of the adjudication that resulted in the ADA */
      adjudicationId: string[]
      prospective: boolean
    }
    /** @description The adjustment and its identifier */
    AdjustmentDto: {
      /**
       * Format: uuid
       * @description The ID of the adjustment
       */
      id?: string
      /**
       * Format: int64
       * @description The NOMIS booking ID of the adjustment
       */
      bookingId: number
      /** @description The NOMIS ID of the person this adjustment applies to */
      person: string
      /**
       * @description The type of adjustment
       * @enum {string}
       */
      adjustmentType:
        | 'REMAND'
        | 'TAGGED_BAIL'
        | 'UNLAWFULLY_AT_LARGE'
        | 'LAWFULLY_AT_LARGE'
        | 'ADDITIONAL_DAYS_AWARDED'
        | 'RESTORATION_OF_ADDITIONAL_DAYS_AWARDED'
        | 'SPECIAL_REMISSION'
        | 'UNUSED_DEDUCTIONS'
        | 'CUSTODY_ABROAD'
        | 'APPEAL_APPLICANT'
      /**
       * Format: date
       * @description The end date of the adjustment
       */
      toDate?: string
      /**
       * Format: date
       * @description The start date of the adjustment
       */
      fromDate?: string
      /**
       * Format: int32
       * @description The number of days of the adjustment
       */
      days?: number
      remand?: components['schemas']['RemandDto']
      additionalDaysAwarded?: components['schemas']['AdditionalDaysAwardedDto']
      unlawfullyAtLarge?: components['schemas']['UnlawfullyAtLargeDto']
      lawfullyAtLarge?: components['schemas']['LawfullyAtLargeDto']
      specialRemission?: components['schemas']['SpecialRemissionDto']
      taggedBail?: components['schemas']['TaggedBailDto']
      timeSpentInCustodyAbroad?: components['schemas']['TimeSpentInCustodyAbroadDto']
      timeSpentAsAnAppealApplicant?: components['schemas']['TimeSpentAsAnAppealApplicantDto']
      /**
       * Format: int32
       * @description The NOMIS sentence sequence of the adjustment
       */
      sentenceSequence?: number
      /**
       * Format: uuid
       * @description The ID of a recall that may be associated to the adjustment
       */
      recallId?: string
      /** @description Human readable text for type of adjustment */
      readonly adjustmentTypeText?: string
      /**
       * @description Indicates whether the adjustment was an addition or deduction
       * @enum {string}
       */
      readonly adjustmentArithmeticType?: 'ADDITION' | 'DEDUCTION' | 'NONE'
      /**
       * @description The name name of the prison where the prisoner was located at the time the adjustment was created
       * @example Leeds
       */
      readonly prisonName?: string
      /**
       * @description The prison where the prisoner was located at the time the adjustment was created (a 3 character code identifying the prison)
       * @example LDS
       */
      readonly prisonId?: string
      /** @description The person last updating this adjustment */
      readonly lastUpdatedBy?: string
      /**
       * @description The status of this adjustment
       * @enum {string}
       */
      readonly status?: 'ACTIVE' | 'INACTIVE' | 'DELETED' | 'INACTIVE_WHEN_DELETED'
      /**
       * Format: date-time
       * @description The date and time this adjustment was last updated
       */
      readonly lastUpdatedDate?: string
      /**
       * Format: date-time
       * @description The date and time this adjustment was last created
       */
      readonly createdDate?: string
      /**
       * Format: int32
       * @description The number of days effective in a calculation. (for example remand minus any unused deductions)
       */
      readonly effectiveDays?: number
      /**
       * @description Where was the adjustment last changed
       * @enum {string}
       */
      readonly source?: 'NOMIS' | 'DPS'
    }
    /** @description The details of a LAL adjustment */
    LawfullyAtLargeDto: {
      /**
       * @description The type of LAL
       * @enum {string}
       */
      affectsDates?: 'YES' | 'NO'
    }
    /** @description The details of remand adjustment */
    RemandDto: {
      /** @description The id of the charges this remand applies to */
      chargeId: number[]
    }
    /** @description The details of a Special Remission adjustment */
    SpecialRemissionDto: {
      /**
       * @description The type of Special Remission
       * @enum {string}
       */
      type?: 'MERITORIOUS_CONDUCT' | 'RELEASE_DATE_CALCULATED_TOO_EARLY' | 'RELEASE_IN_ERROR'
    }
    /** @description The details of the tagged bail adjustment */
    TaggedBailDto: {
      /**
       * Format: int32
       * @description The case sequence number this tagged-bail was associated with
       */
      caseSequence?: number
      /**
       * Format: uuid
       * @description The dps court case id this tagged-bail was associated with
       */
      courtCaseUuid?: string
    }
    /** @description The details of the time spent as an appeal applicant adjustment */
    TimeSpentAsAnAppealApplicantDto: {
      /** @description The court of appeal reference number for the time spent as an appeal applicant adjustment */
      courtOfAppealReferenceNumber?: string
      /** @description The id of the charges for this time spent as an appeal applicant */
      chargeIds: number[]
    }
    /** @description The details of the time spent in custody abroad adjustment */
    TimeSpentInCustodyAbroadDto: {
      /**
       * @description The source document for the time spent in custody abroad information
       * @enum {string}
       */
      documentationSource?: 'COURT_WARRANT' | 'PPCS_LETTER'
      /** @description The id of the charges for this time spent in custody abroad adjustment */
      chargeIds: number[]
    }
    /** @description The details of a UAL adjustment */
    UnlawfullyAtLargeDto: {
      /**
       * @description The type of UAL
       * @enum {string}
       */
      type?: 'RECALL' | 'ESCAPE' | 'SENTENCED_IN_ABSENCE' | 'RELEASE_IN_ERROR' | 'IMMIGRATION_DETENTION'
    }
    LegacyAdjustmentCreatedResponse: {
      /** Format: uuid */
      adjustmentId: string
    }
    CreateResponseDto: {
      adjustmentIds: string[]
    }
    /** @description Details of the adjustment and the number of effective days within a calculation. */
    AdjustmentEffectiveDaysDto: {
      /**
       * Format: uuid
       * @description The ID of the adjustment
       */
      id: string
      /**
       * Format: int32
       * @description The number of days effective in a calculation. (for example remand minus any unused deductions)
       */
      effectiveDays: number
      /** @description The NOMIS ID of the person this adjustment applies to */
      person: string
    }
    /** @description Validation message details */
    ValidationMessage: {
      /**
       * @description Validation code details
       * @enum {string}
       */
      code:
        | 'RADA_FROM_DATE_NOT_NULL'
        | 'RADA_REDUCES_BY_MORE_THAN_HALF'
        | 'MORE_RADAS_THAN_ADAS'
        | 'RADA_DATE_CANNOT_BE_FUTURE'
        | 'RADA_DATA_MUST_BE_AFTER_SENTENCE_DATE'
        | 'RADA_DAYS_MUST_BE_POSTIVE'
        | 'UAL_FROM_DATE_NOT_NULL'
        | 'UAL_TO_DATE_NOT_NULL'
        | 'UAL_FROM_DATE_AFTER_TO_DATE'
        | 'UAL_TYPE_NOT_NULL'
        | 'UAL_FIRST_DATE_CANNOT_BE_FUTURE'
        | 'UAL_LAST_DATE_CANNOT_BE_FUTURE'
        | 'UAL_DATE_MUST_BE_AFTER_SENTENCE_DATE'
        | 'LAL_FROM_DATE_NOT_NULL'
        | 'LAL_TO_DATE_NOT_NULL'
        | 'LAL_FROM_DATE_AFTER_TO_DATE'
        | 'LAL_AFFECTS_DATES_NOT_NULL'
        | 'LAL_FIRST_DATE_CANNOT_BE_FUTURE'
        | 'LAL_LAST_DATE_CANNOT_BE_FUTURE'
        | 'LAL_DATE_MUST_BE_AFTER_SENTENCE_DATE'
        | 'SREM_TYPE_NOT_NULL'
        | 'TCA_DOCUMENTATION_SOURCE_NOT_NULL'
        | 'TSA_COURT_OF_APPEAL_REFERENCE_NOT_NULL'
        | 'TSA_COURT_OF_APPEAL_REFERENCE_WRONG_LENGTH'
        | 'TSA_COURT_OF_APPEAL_REFERENCE_INVALID_CHARACTERS'
      arguments: string[]
      message: string
      /** @enum {string} */
      type: 'VALIDATION' | 'WARNING'
    }
    /** @description The adjustment UUID */
    RestoreAdjustmentsDto: {
      /** @description The IDs of the adjustments to restore */
      ids: string[]
    }
    /** @description Details of the number of unused days */
    ManualUnusedDeductionsDto: {
      /**
       * Format: int32
       * @description The number of unused days
       */
      days: number
    }
    /** @description The DTO representing the PADAs rejected */
    ProspectiveAdaRejectionDto: {
      /** @description The NOMIS ID of the person this pada is rejected applies to */
      person: string
      /**
       * Format: int32
       * @description The number of days that were rejected
       */
      days: number
      /**
       * Format: date
       * @description The date of the charges proved that were rejected
       */
      dateChargeProved: string
    }
    /** @description Will be populated if there is a ADA_INTERCEPT in the thingsToDo */
    AdaIntercept: {
      /** @enum {string} */
      type: 'NONE' | 'FIRST_TIME_WITH_NO_ADJUDICATION' | 'FIRST_TIME' | 'UPDATE' | 'PADAS' | 'PADA'
      /** Format: int32 */
      number: number
      anyProspective: boolean
      messageArguments: string[]
      message?: string
    } | null
    ThingsToDo: {
      prisonerId: string
      thingsToDo: 'ADA_INTERCEPT'[]
      adaIntercept?: components['schemas']['AdaIntercept']
    }
    DlqMessage: {
      body: {
        [key: string]: Record<string, never>
      }
      messageId: string
    }
    GetDlqResult: {
      /** Format: int32 */
      messagesFoundCount: number
      /** Format: int32 */
      messagesReturnedCount: number
      messages: components['schemas']['DlqMessage'][]
    }
    UnusedDeductionsCalculationResultDto: {
      person: string
      /** Format: date-time */
      calculationAt: string
      /** @enum {string} */
      status: 'NOMIS_ADJUSTMENT' | 'VALIDATION' | 'UNSUPPORTED' | 'RECALL' | 'UNKNOWN' | 'CALCULATED' | 'IN_PROGRESS'
    }
    Ada: {
      /** Format: date */
      dateChargeProved: string
      chargeNumber: string
      toBeServed?: string
      heardAt?: string
      /** @enum {string} */
      status: 'AWARDED_OR_PENDING' | 'SUSPENDED' | 'QUASHED' | 'PROSPECTIVE'
      /** Format: int32 */
      days: number
      consecutiveToChargeNumber?: string
    }
    AdaAdjudicationDetails: {
      awarded: components['schemas']['AdasByDateCharged'][]
      /** Format: int32 */
      totalAwarded: number
      suspended: components['schemas']['AdasByDateCharged'][]
      /** Format: int32 */
      totalSuspended: number
      quashed: components['schemas']['AdasByDateCharged'][]
      /** Format: int32 */
      totalQuashed: number
      awaitingApproval: components['schemas']['AdasByDateCharged'][]
      /** Format: int32 */
      totalAwaitingApproval: number
      prospective: components['schemas']['AdasByDateCharged'][]
      /** Format: int32 */
      totalProspective: number
      intercept: components['schemas']['AdaIntercept']
      /** Format: int32 */
      totalExistingAdas: number
      showExistingAdaMessage: boolean
      recallWithMissingOutcome: boolean
      /** Format: date */
      earliestNonRecallSentenceDate?: string
      /** Format: date */
      earliestRecallDate?: string
    }
    AdasByDateCharged: {
      /** Format: date */
      dateChargeProved: string
      charges: components['schemas']['Ada'][]
      /** Format: int32 */
      total?: number
      /** @enum {string} */
      status?: 'AWARDED' | 'PENDING_APPROVAL' | 'SUSPENDED' | 'QUASHED' | 'PROSPECTIVE'
      /** Format: uuid */
      adjustmentId?: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  retryDlq: {
    parameters: {
      query?: never
      header?: never
      path: {
        dlqName: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RetryDlqResult']
        }
      }
    }
  }
  retryAllDlqs: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RetryDlqResult'][]
        }
      }
    }
  }
  purgeQueue: {
    parameters: {
      query?: never
      header?: never
      path: {
        queueName: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['PurgeQueueResult']
        }
      }
    }
  }
  get: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The adjustment UUID */
        adjustmentId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Adjustment found */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LegacyAdjustment']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LegacyAdjustment']
        }
      }
      /** @description Adjustment not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LegacyAdjustment']
        }
      }
    }
  }
  update: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The adjustment UUID */
        adjustmentId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/vnd.nomis-offence+json': components['schemas']['LegacyAdjustment']
      }
    }
    responses: {
      /** @description Adjustment update */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Adjustment not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The adjustment UUID */
        adjustmentId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Adjustment deleted */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Adjustment not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  get_1: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The adjustment UUID */
        adjustmentId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Adjustment found */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AdjustmentDto']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AdjustmentDto']
        }
      }
      /** @description Adjustment not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AdjustmentDto']
        }
      }
    }
  }
  update_1: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The adjustment UUID */
        adjustmentId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AdjustmentDto']
      }
    }
    responses: {
      /** @description Adjustment update */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Adjustment not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  delete_1: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The adjustment UUID */
        adjustmentId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Adjustment deleted */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Adjustment not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/vnd.nomis-offence+json': components['schemas']['LegacyAdjustment']
      }
    }
    responses: {
      /** @description Adjustment created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LegacyAdjustmentCreatedResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LegacyAdjustmentCreatedResponse']
        }
      }
    }
  }
  migration: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/vnd.nomis-offence+json': components['schemas']['LegacyAdjustment']
      }
    }
    responses: {
      /** @description Adjustment created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LegacyAdjustmentCreatedResponse']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LegacyAdjustmentCreatedResponse']
        }
      }
    }
  }
  findByPerson: {
    parameters: {
      query: {
        /** @description The noms ID of the person */
        person: string
        /** @description The status of adjustments. Defaults to ACTIVE */
        status?: ('ACTIVE' | 'INACTIVE' | 'DELETED' | 'INACTIVE_WHEN_DELETED')[]
        /** @description Only get the adjustments linked to the current period of custody. Defaults to true */
        currentPeriodOfCustody?: boolean
        /** @description The earliest sentence date to filter adjustments by. Defaults to earliest active sentence date */
        sentenceEnvelopeDate?: string
        /** @description The recall ID to filter adjustments by. */
        recallId?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Adjustment found */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AdjustmentDto'][]
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AdjustmentDto'][]
        }
      }
      /** @description Adjustment not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AdjustmentDto'][]
        }
      }
    }
  }
  create_1: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AdjustmentDto'][]
      }
    }
    responses: {
      /** @description Adjustments created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CreateResponseDto']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CreateResponseDto']
        }
      }
    }
  }
  updateEffectiveDays: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The adjustment UUID */
        adjustmentId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AdjustmentEffectiveDaysDto']
      }
    }
    responses: {
      /** @description Adjustment update */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Adjustment not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  validate: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AdjustmentDto']
      }
    }
    responses: {
      /** @description Adjustment validation returned */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ValidationMessage'][]
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ValidationMessage'][]
        }
      }
    }
  }
  restore: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RestoreAdjustmentsDto']
      }
    }
    responses: {
      /** @description Adjustment restored */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Adjustment not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  setUnusedDaysManually: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The person */
        person: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ManualUnusedDeductionsDto']
      }
    }
    responses: {
      /** @description Adjustment update */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Adjustment not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  rejectProspectiveAda: {
    parameters: {
      query?: never
      header?: never
      path: {
        /**
         * @description The noms ID of the person
         * @example AA1256A
         */
        person: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ProspectiveAdaRejectionDto']
      }
    }
    responses: {
      /** @description Reject a prospective ADA */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Adjustment not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  setCurrentTerm: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The adjustment UUID */
        adjustmentId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/vnd.nomis-offence+json': components['schemas']['LegacyAdjustment']
      }
    }
    responses: {
      /** @description Adjustment updated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Adjustment not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  getThingsToDo: {
    parameters: {
      query?: never
      header?: never
      path: {
        /**
         * @description Prisoner's ID (also known as nomsId)
         * @example A1234AB
         */
        prisonerId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successfully returns the things-to-do list */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ThingsToDo']
        }
      }
      /** @description Unauthorized - valid Oauth2 token required */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ThingsToDo']
        }
      }
      /** @description Forbidden - requires appropriate role */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ThingsToDo']
        }
      }
    }
  }
  getDlqMessages: {
    parameters: {
      query?: {
        maxMessages?: number
      }
      header?: never
      path: {
        dlqName: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['GetDlqResult']
        }
      }
    }
  }
  getUnusedDeductionsResult: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The person */
        person: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Returns result */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UnusedDeductionsCalculationResultDto']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UnusedDeductionsCalculationResultDto']
        }
      }
      /** @description Person not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UnusedDeductionsCalculationResultDto']
        }
      }
    }
  }
  getAdaAdjudicationDetails: {
    parameters: {
      query?: {
        /**
         * @description The dates of selected prospective adas
         * @example 2022-01-10,2022-02-11
         */
        selectedProspectiveAdaDates?: string[]
      }
      header?: never
      path: {
        /**
         * @description The noms ID of the person
         * @example AA1256A
         */
        person: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Details of adjudications and adjustments returned */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AdaAdjudicationDetails']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AdaAdjudicationDetails']
        }
      }
      /** @description Adjustment not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AdaAdjudicationDetails']
        }
      }
    }
  }
}
