generic-service:
  nameOverride: hmpps-record-a-recall
  productId: "DPS014" # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  # the IRSA service account name for accessing AWS resources
  # serviceAccountName: "hmpps-record-a-recall"

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-record-a-recall
    tag: app_version # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: record-a-recall-cert

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  # Environment variables to load into the deployment
  env:
    NODE_ENV: "production"
    REDIS_ENABLED: "true"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"
    AUDIT_SQS_REGION: "eu-west-2"
    AUDIT_SERVICE_NAME: "UNASSIGNED" # Your audit service name
    COMPONENT_API_URL: "https://frontend-components-dev.hmpps.service.justice.gov.uk"
    UNEXPECTED_RECALL_TYPE_CHECK_ENABLED: "false"
    USE_V2_RECALL_FLOW: "true"
  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-record-a-recall-client-creds:
      CLIENT_CREDS_CLIENT_ID: 'CLIENT_CREDS_CLIENT_ID'
      CLIENT_CREDS_CLIENT_SECRET: 'CLIENT_CREDS_CLIENT_SECRET'
    hmpps-record-a-recall-auth-code:
      AUTH_CODE_CLIENT_ID: 'AUTH_CODE_CLIENT_ID'
      AUTH_CODE_CLIENT_SECRET: 'AUTH_CODE_CLIENT_SECRET'
    hmpps-record-a-recall-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    hmpps-record-a-recall-session-secret:
      SESSION_SECRET: 'SESSION_SECRET'
    elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"
    #sqs-hmpps-audit-secret:
    #  AUDIT_SQS_QUEUE_URL: "sqs_queue_url"
    #  AUDIT_SQS_QUEUE_NAME: "sqs_queue_name"

  allowlist:
    ark-dom1-farnborough: 194.33.192.0/24
    ark-dom1-corsham: 194.33.196.0/24
    cymulate-1: 54.217.50.18/32
    cymulate-2: 52.208.202.111/32
    cymulate-3: 52.49.144.209/32
    groups:
      - internal
      - prisons
      - private_prisons

generic-prometheus-alerts:
  targetApplication: hmpps-record-a-recall
