import HmppsAuditClient, { AuditEvent } from '../data/hmppsAuditClient'

export enum Page {
  HOME = 'HOME',
  START_CREATE_RECALL = 'START_CREATE_RECALL',
  START_EDIT_RECALL = 'START_EDIT_RECALL',
  ENTER_REVOCATION_DATE = 'ENTER_REVOCATION_DATE',
  ENTER_RETURN_TO_CUSTODY_DATE = 'ENTER_RETURN_TO_CUSTODY_DATE',
  DECISION = 'DECISION',
  REVIEW_SENTENCES_AUTOMATED = 'REVIEW_SENTENCES_AUTOMATED',
  CRITICAL_VALIDATION_INTERCEPT = 'CRITICAL_VALIDATION_INTERCEPT',
  CONFLICTING_ADJUSTMENTS_INTERCEPT = 'CONFLICTING_ADJUSTMENTS_INTERCEPT',
  NO_RECALLABLE_SENTENCES_INTERCEPT = 'NO_RECALLABLE_SENTENCES_INTERCEPT',
  UNEXPECTED_RECALL_TYPE_INTERCEPT = 'UNEXPECTED_RECALL_TYPE_INTERCEPT',
  UNSUPPORTED_RECALL_TYPE_INTERCEPT = 'UNSUPPORTED_RECALL_TYPE_INTERCEPT',
  UNKNOWN_PRE_RECALL_SENTENCE_TYPE_INTERCEPT = 'UNKNOWN_PRE_RECALL_SENTENCE_TYPE_INTERCEPT',
  CONFIRMATION = 'CONFIRMATION',
  CHECK_ANSWERS = 'CHECK_ANSWERS',
  TYPE_AUTOMATED = 'TYPE_AUTOMATED',
  MANUAL_INTERCEPT = 'MANUAL_INTERCEPT',
  MANUAL_SELECT_CASES = 'MANUAL_SELECT_CASES',
  MANUAL_CHECK_SENTENCES = 'MANUAL_CHECK_SENTENCES',
  MANAUL_SELECT_TYPE = 'MANAUL_SELECT_TYPE',
  MANUAL_CHECK_ANSWERS = 'MANUAL_CHECK_ANSWERS',
  CONFIRM_DELETE_RECALL = 'CONFIRM_DELETE_RECALL',
  CANCEL = 'CANCEL',
}

export interface PageViewEventDetails {
  who: string
  subjectId?: string
  subjectType?: string
  correlationId?: string
  details?: object
}

export default class AuditService {
  constructor(private readonly hmppsAuditClient: HmppsAuditClient) {}

  async logAuditEvent(event: AuditEvent) {
    await this.hmppsAuditClient.sendMessage(event)
  }

  async logPageView(page: Page, eventDetails: PageViewEventDetails) {
    const event: AuditEvent = {
      ...eventDetails,
      what: `PAGE_VIEW_${page}`,
    }
    await this.hmppsAuditClient.sendMessage(event)
  }
}
