import { SuperAgentRequest } from 'superagent'
import { stubFor } from './wiremock'

export default {
  stubPing: (httpStatus = 200): SuperAgentRequest =>
    stubFor({
      request: {
        method: 'GET',
        urlPath: '/prison-search-api/health/ping',
      },
      response: {
        status: httpStatus,
        headers: { 'Content-Type': 'application/json;charset=UTF-8' },
        jsonBody: { status: httpStatus === 200 ? 'UP' : 'DOWN' },
      },
    }),
  stubPrisonerSearch: (): SuperAgentRequest => {
    return stubFor({
      request: {
        method: 'GET',
        urlPattern: '/prison-search-api/prisoner/A1234AB',
      },
      response: {
        status: 200,
        headers: { 'Content-Type': 'application/json;charset=UTF-8' },
        jsonBody: {
          prisonerNumber: 'A1234AB',
          pncNumber: '12/394773H',
          pncNumberCanonicalShort: '12/394773H',
          pncNumberCanonicalLong: '2012/394773H',
          croNumber: '29906/12J',
          bookingId: '0001200924',
          bookNumber: '38412A',
          title: 'Ms',
          firstName: 'Robert',
          middleNames: 'John James',
          lastName: 'Larsen',
          dateOfBirth: '1975-04-02',
          gender: 'Female',
          ethnicity: 'White: Eng./Welsh/Scot./N.Irish/British',
          youthOffender: true,
          maritalStatus: 'Widowed',
          religion: 'Church of England (Anglican)',
          nationality: 'Egyptian',
          status: 'ACTIVE IN',
          lastMovementTypeCode: 'CRT',
          lastMovementReasonCode: 'CA',
          inOutStatus: 'IN',
          prisonId: 'MDI',
          lastPrisonId: 'MDI',
          prisonName: 'HMP Leeds',
          cellLocation: 'A-1-002',
          aliases: [],
          alerts: [],
          csra: 'HIGH',
          category: 'C',
          legalStatus: 'SENTENCED',
          imprisonmentStatus: 'LIFE',
          imprisonmentStatusDescription: 'Serving Life Imprisonment',
          mostSeriousOffence: 'Robbery',
          recall: false,
          indeterminateSentence: true,
          sentenceStartDate: '2020-04-03',
          releaseDate: '2023-05-02',
          confirmedReleaseDate: '2023-05-01',
          sentenceExpiryDate: '2023-05-01',
          licenceExpiryDate: '2023-05-01',
          homeDetentionCurfewEligibilityDate: '2023-05-01',
          homeDetentionCurfewActualDate: '2023-05-01',
          homeDetentionCurfewEndDate: '2023-05-02',
          topupSupervisionStartDate: '2023-04-29',
          topupSupervisionExpiryDate: '2023-05-01',
          additionalDaysAwarded: 10,
          nonDtoReleaseDate: '2023-05-01',
          nonDtoReleaseDateType: 'ARD',
          receptionDate: '2023-05-01',
          paroleEligibilityDate: '2023-05-01',
          automaticReleaseDate: '2023-05-01',
          postRecallReleaseDate: '2023-05-01',
          conditionalReleaseDate: '2023-05-01',
          actualParoleDate: '2023-05-01',
          tariffDate: '2023-05-01',
          releaseOnTemporaryLicenceDate: '2023-05-01',
          locationDescription: 'Outside - released from Leeds',
          restrictedPatient: true,
          supportingPrisonId: 'LEI',
          dischargedHospitalId: 'HAZLWD',
          dischargedHospitalDescription: 'Hazelwood House',
          dischargeDate: '2020-05-01',
          dischargeDetails: 'Psychiatric Hospital Discharge to Hazelwood House',
          currentIncentive: {},
          heightCentimetres: 200,
          weightKilograms: 102,
          hairColour: 'Blonde',
          rightEyeColour: 'Green',
          leftEyeColour: 'Hazel',
          facialHair: 'Clean Shaven',
          shapeOfFace: 'Round',
          build: 'Muscular',
          shoeSize: 10,
          tattoos: [],
          scars: [],
          marks: [],
          addresses: [],
          emailAddresses: [],
          phoneNumbers: [],
          identifiers: [],
          allConvictedOffences: [],
        },
      },
    })
  },
  //   return stubFor({
  //     request: {
  //       method: 'GET',
  //       urlPattern: '/prison-search-api/prisoner/BA1234AB',
  //     },
  //     response: {
  //       status: 200,
  //       headers: { 'Content-Type': 'application/json;charset=UTF-8' },
  //       jsonBody: {
  //         prisonerNumber: 'BA1234AB',
  //         pncNumber: '12/394773H',
  //         pncNumberCanonicalShort: '12/394773H',
  //         pncNumberCanonicalLong: '2012/394773H',
  //         croNumber: '29906/12J',
  //         bookingId: '0001200924',
  //         bookNumber: '38412A',
  //         title: 'Ms',
  //         firstName: 'Roberta',
  //         middleNames: 'John James',
  //         lastName: 'Larsen',
  //         dateOfBirth: '1975-04-02',
  //         gender: 'Female',
  //         ethnicity: 'White: Eng./Welsh/Scot./N.Irish/British',
  //         youthOffender: true,
  //         maritalStatus: 'Widowed',
  //         religion: 'Church of England (Anglican)',
  //         nationality: 'Egyptian',
  //         status: 'ACTIVE IN',
  //         lastMovementTypeCode: 'CRT',
  //         lastMovementReasonCode: 'CA',
  //         inOutStatus: 'IN',
  //         prisonId: 'MDI',
  //         lastPrisonId: 'MDI',
  //         prisonName: 'HMP Leeds',
  //         cellLocation: 'A-1-002',
  //         aliases: [],
  //         alerts: [],
  //         csra: 'HIGH',
  //         category: 'C',
  //         legalStatus: 'SENTENCED',
  //         imprisonmentStatus: 'LIFE',
  //         imprisonmentStatusDescription: 'Serving Life Imprisonment',
  //         mostSeriousOffence: 'Robbery',
  //         recall: false,
  //         indeterminateSentence: true,
  //         sentenceStartDate: '2020-04-03',
  //         releaseDate: '2023-05-02',
  //         confirmedReleaseDate: '2023-05-01',
  //         sentenceExpiryDate: '2023-05-01',
  //         licenceExpiryDate: '2023-05-01',
  //         homeDetentionCurfewEligibilityDate: '2023-05-01',
  //         homeDetentionCurfewActualDate: '2023-05-01',
  //         homeDetentionCurfewEndDate: '2023-05-02',
  //         topupSupervisionStartDate: '2023-04-29',
  //         topupSupervisionExpiryDate: '2023-05-01',
  //         additionalDaysAwarded: 10,
  //         nonDtoReleaseDate: '2023-05-01',
  //         nonDtoReleaseDateType: 'ARD',
  //         receptionDate: '2023-05-01',
  //         paroleEligibilityDate: '2023-05-01',
  //         automaticReleaseDate: '2023-05-01',
  //         postRecallReleaseDate: '2023-05-01',
  //         conditionalReleaseDate: '2023-05-01',
  //         actualParoleDate: '2023-05-01',
  //         tariffDate: '2023-05-01',
  //         releaseOnTemporaryLicenceDate: '2023-05-01',
  //         locationDescription: 'Outside - released from Leeds',
  //         restrictedPatient: true,
  //         supportingPrisonId: 'LEI',
  //         dischargedHospitalId: 'HAZLWD',
  //         dischargedHospitalDescription: 'Hazelwood House',
  //         dischargeDate: '2020-05-01',
  //         dischargeDetails: 'Psychiatric Hospital Discharge to Hazelwood House',
  //         currentIncentive: {},
  //         heightCentimetres: 200,
  //         weightKilograms: 102,
  //         hairColour: 'Blonde',
  //         rightEyeColour: 'Green',
  //         leftEyeColour: 'Hazel',
  //         facialHair: 'Clean Shaven',
  //         shapeOfFace: 'Round',
  //         build: 'Muscular',
  //         shoeSize: 10,
  //         tattoos: [],
  //         scars: [],
  //         marks: [],
  //         addresses: [],
  //         emailAddresses: [],
  //         phoneNumbers: [],
  //         identifiers: [],
  //         allConvictedOffences: [],
  //       },
  //     },
  //   })
  // },
  stubPrisonerSearchNonManual: (): SuperAgentRequest => {
    return stubFor({
      request: {
        method: 'GET',
        urlPattern: '/prison-search-api/prisoner/A0164ED',
      },
      response: {
        status: 200,
        headers: { 'Content-Type': 'application/json;charset=UTF-8' },
        jsonBody: {
          prisonerNumber: 'A0164ED',
          bookingId: '1233536',
          bookNumber: '70229A',
          firstName: 'VANILLA',
          lastName: 'RECALLS',
          dateOfBirth: '1980-01-01',
          gender: 'Male',
          youthOffender: false,
          personalCareNeeds: [],
          languages: [],
          militaryRecord: false,
          status: 'ACTIVE IN',
          lastMovementTypeCode: 'ADM',
          lastMovementReasonCode: 'N',
          inOutStatus: 'IN',
          prisonId: 'KMI',
          prisonName: 'Kirkham (HMP)',
          lastPrisonId: 'KMI',
          cellLocation: 'RECP',
          aliases: [],
          alerts: [],
          legalStatus: 'SENTENCED',
          imprisonmentStatus: 'ADIMP_ORA20',
          imprisonmentStatusDescription: 'ORA 2020 Standard Determinate Sentence',
          convictedStatus: 'Convicted',
          mostSeriousOffence: 'Affray',
          recall: false,
          indeterminateSentence: false,
          sentenceStartDate: '2025-04-01',
          receptionDate: '2022-01-01',
          lastAdmissionDate: '2022-01-01',
          locationDescription: 'Kirkham (HMP)',
          restrictedPatient: false,
          currentIncentive: {
            level: {
              code: 'STD',
              description: 'Standard',
            },
            dateTime: '2026-02-11T12:08:49',
            nextReviewDate: '2022-04-01',
          },
          addresses: [],
          emailAddresses: [],
          phoneNumbers: [],
          identifiers: [],
          allConvictedOffences: [
            {
              statuteCode: 'PU86',
              offenceCode: 'PU86003',
              offenceDescription: 'Affray',
              offenceDate: '2020-01-01',
              latestBooking: true,
              sentenceStartDate: '2025-04-01',
              primarySentence: true,
            },
          ],
        },
      },
    })
  },
}
