import { SuperAgentRequest } from 'superagent'
import { stubFor } from './wiremock'

export default {
  stubSearchCourtCases: ({ sortBy = 'desc' }: { sortBy: string }): SuperAgentRequest => {
    return stubFor({
      request: {
        method: 'GET',
        urlPath: '/remand-and-sentencing-api/court-case/search',
        queryParameters: {
          prisonerId: {
            equalTo: 'A1234AB', // Note: This was the original prisonerId in the stub, the data you provided uses 'A1234AB'. You may need to align these.
          },
          sort: {
            equalTo: `latestCourtAppearance_appearanceDate,${sortBy}`,
          },
        },
      },
      response: {
        status: 200,
        headers: { 'Content-Type': 'application/json;charset=UTF-8' },
        jsonBody: {
          content: [
            {
              prisonerId: 'A1234AB',
              courtCaseUuid: 'bbb25c4f-81d7-4e18-ad84-0646a54c8a3a',
              status: 'ACTIVE',
              latestAppearance: {
                appearanceUuid: '26c7300b-72ae-4c52-8cc7-48a4a4dd1edc',
                outcome: {
                  outcomeUuid: '62412083-9892-48c9-bf01-7864af4a8b3c',
                  outcomeName: 'Imprisonment',
                  nomisCode: '1002',
                  outcomeType: 'SENTENCING',
                  displayOrder: 10,
                  relatedChargeOutcomeUuid: 'f17328cf-ceaa-43c2-930a-26cf74480e18',
                  isSubList: false,
                },
                courtCode: 'ABRYCT',
                courtCaseReference: null,
                appearanceDate: '2023-06-12',
                warrantId: null,
                warrantType: 'SENTENCING',
                nextCourtAppearance: null,
                charges: [
                  {
                    chargeUuid: '3bc7fadc-67e8-44d6-8fc0-cd61bffc4895',
                    offenceCode: 'HA04005',
                    offenceStartDate: '2021-09-26',
                    offenceEndDate: null,
                    outcome: {
                      outcomeUuid: 'f17328cf-ceaa-43c2-930a-26cf74480e18',
                      outcomeName: 'Imprisonment',
                      nomisCode: '1002',
                      outcomeType: 'SENTENCING',
                      displayOrder: 10,
                      dispositionCode: 'FINAL',
                    },
                    terrorRelated: null,
                    sentence: {
                      sentenceUuid: 'a669b3a0-1ddc-4f4d-80b8-468b4ea529f8',
                      chargeNumber: null,
                      periodLengths: [
                        {
                          years: 1,
                          months: null,
                          weeks: null,
                          days: null,
                          periodOrder: 'years,months,weeks,days',
                          periodLengthType: 'CUSTODIAL_TERM',
                          legacyData: null,
                          periodLengthUuid: 'fc003e29-ede9-4302-b970-27ab3b6a11e4',
                        },
                        {
                          years: 5,
                          months: null,
                          weeks: null,
                          days: null,
                          periodOrder: 'years,months,weeks,days',
                          periodLengthType: 'LICENCE_PERIOD',
                          legacyData: null,
                          periodLengthUuid: '8c5ac995-db1e-4cdf-9acd-56aa6abc99f6',
                        },
                      ],
                      sentenceServeType: 'CONCURRENT',
                      sentenceType: {
                        sentenceTypeUuid: '0da58738-2db6-4fba-8f65-438284019756',
                        description: 'EDS (Extended Determinate Sentence)',
                        classification: 'EXTENDED',
                        hintText: null,
                        displayOrder: 20,
                      },
                      convictionDate: null,
                      fineAmount: null,
                      legacyData: {
                        sentenceCalcType: null,
                        sentenceCategory: null,
                        sentenceTypeDesc: null,
                        postedDate: '2025-06-12T10:59:45.378275',
                        active: true,
                        nomisLineReference: '2',
                      },
                      consecutiveToSentenceUuid: null,
                      hasRecall: false,
                    },
                    legacyData: {
                      postedDate: '2025-06-12',
                      nomisOutcomeCode: null,
                      outcomeDescription: null,
                      outcomeDispositionCode: null,
                      outcomeConvictionFlag: true,
                    },
                  },
                ],
                overallSentenceLength: null,
                overallConvictionDate: null,
                legacyData: {
                  postedDate: '2025-06-12',
                  nomisOutcomeCode: '1002',
                  outcomeDescription: 'Imprisonment',
                  nextEventDateTime: null,
                  appearanceTime: '10:00:00',
                  outcomeDispositionCode: 'F',
                  outcomeConvictionFlag: true,
                },
              },
              appearances: [
                {
                  appearanceUuid: '26c7300b-72ae-4c52-8cc7-48a4a4dd1edc',
                  outcome: {
                    outcomeUuid: '62412083-9892-48c9-bf01-7864af4a8b3c',
                    outcomeName: 'Imprisonment',
                    nomisCode: '1002',
                    outcomeType: 'SENTENCING',
                    displayOrder: 10,
                    relatedChargeOutcomeUuid: 'f17328cf-ceaa-43c2-930a-26cf74480e18',
                    isSubList: false,
                  },
                  courtCode: 'ABRYCT',
                  courtCaseReference: null,
                  appearanceDate: '2023-06-12',
                  warrantId: null,
                  warrantType: 'SENTENCING',
                  nextCourtAppearance: null,
                  charges: [
                    {
                      chargeUuid: '3bc7fadc-67e8-44d6-8fc0-cd61bffc4895',
                      offenceCode: 'HA04005',
                      offenceStartDate: '2021-09-26',
                      offenceEndDate: null,
                      outcome: {
                        outcomeUuid: 'f17328cf-ceaa-43c2-930a-26cf74480e18',
                        outcomeName: 'Imprisonment',
                        nomisCode: '1002',
                        outcomeType: 'SENTENCING',
                        displayOrder: 10,
                        dispositionCode: 'FINAL',
                      },
                      terrorRelated: null,
                      sentence: {
                        sentenceUuid: 'a669b3a0-1ddc-4f4d-80b8-468b4ea529f8',
                        chargeNumber: null,
                        periodLengths: [
                          {
                            years: 1,
                            months: null,
                            weeks: null,
                            days: null,
                            periodOrder: 'years,months,weeks,days',
                            periodLengthType: 'CUSTODIAL_TERM',
                            legacyData: null,
                            periodLengthUuid: 'fc003e29-ede9-4302-b970-27ab3b6a11e4',
                          },
                          {
                            years: 5,
                            months: null,
                            weeks: null,
                            days: null,
                            periodOrder: 'years,months,weeks,days',
                            periodLengthType: 'LICENCE_PERIOD',
                            legacyData: null,
                            periodLengthUuid: '8c5ac995-db1e-4cdf-9acd-56aa6abc99f6',
                          },
                        ],
                        sentenceServeType: 'CONCURRENT',
                        sentenceType: {
                          sentenceTypeUuid: '0da58738-2db6-4fba-8f65-438284019756',
                          description: 'EDS (Extended Determinate Sentence)',
                          classification: 'EXTENDED',
                          hintText: null,
                          displayOrder: 20,
                        },
                        convictionDate: null,
                        fineAmount: null,
                        legacyData: {
                          sentenceCalcType: null,
                          sentenceCategory: null,
                          sentenceTypeDesc: null,
                          postedDate: '2025-06-12T10:59:45.378275',
                          active: true,
                          nomisLineReference: '2',
                        },
                        consecutiveToSentenceUuid: null,
                        hasRecall: false,
                      },
                      legacyData: {
                        postedDate: '2025-06-12',
                        nomisOutcomeCode: null,
                        outcomeDescription: null,
                        outcomeDispositionCode: null,
                        outcomeConvictionFlag: true,
                      },
                    },
                  ],
                  overallSentenceLength: null,
                  overallConvictionDate: null,
                  legacyData: {
                    postedDate: '2025-06-12',
                    nomisOutcomeCode: '1002',
                    outcomeDescription: 'Imprisonment',
                    nextEventDateTime: null,
                    appearanceTime: '10:00:00',
                    outcomeDispositionCode: 'F',
                    outcomeConvictionFlag: true,
                  },
                },
              ],
              legacyData: null,
            },
            {
              prisonerId: 'A1234AB',
              courtCaseUuid: '4eb87827-f43e-48bf-80df-86c7205b581c',
              status: 'ACTIVE',
              latestAppearance: {
                appearanceUuid: '8d173286-0c8b-485b-a671-cc02abdb8b79',
                outcome: {
                  outcomeUuid: '62412083-9892-48c9-bf01-7864af4a8b3c',
                  outcomeName: 'Imprisonment',
                  nomisCode: '1002',
                  outcomeType: 'SENTENCING',
                  displayOrder: 10,
                  relatedChargeOutcomeUuid: 'f17328cf-ceaa-43c2-930a-26cf74480e18',
                  isSubList: false,
                },
                courtCode: 'ABDRCT',
                courtCaseReference: null,
                appearanceDate: '2023-02-12',
                warrantId: null,
                warrantType: 'SENTENCING',
                nextCourtAppearance: null,
                charges: [
                  {
                    chargeUuid: 'e6365327-4478-4355-8e1e-aff35c86a554',
                    offenceCode: 'COML017B',
                    offenceStartDate: '2021-08-03',
                    offenceEndDate: null,
                    outcome: {
                      outcomeUuid: 'f17328cf-ceaa-43c2-930a-26cf74480e18',
                      outcomeName: 'Imprisonment',
                      nomisCode: '1002',
                      outcomeType: 'SENTENCING',
                      displayOrder: 10,
                      dispositionCode: 'FINAL',
                    },
                    terrorRelated: null,
                    sentence: {
                      sentenceUuid: 'b1515f6d-b685-46be-b8a7-3f1f87cca976',
                      chargeNumber: null,
                      periodLengths: [
                        {
                          years: 2,
                          months: 11,
                          weeks: null,
                          days: null,
                          periodOrder: 'years,months,weeks,days',
                          periodLengthType: 'SENTENCE_LENGTH',
                          legacyData: null,
                          periodLengthUuid: 'e7b188ef-066e-40be-b59a-d71f2e109ff9',
                        },
                      ],
                      sentenceServeType: 'CONCURRENT',
                      sentenceType: {
                        sentenceTypeUuid: '02fe3513-40a6-47e9-a72d-9dafdd936a0e',
                        description: 'SDS (Standard Determinate Sentence)',
                        classification: 'STANDARD',
                        hintText: null,
                        displayOrder: 10,
                      },
                      convictionDate: null,
                      fineAmount: null,
                      legacyData: {
                        sentenceCalcType: null,
                        sentenceCategory: null,
                        sentenceTypeDesc: null,
                        postedDate: '2025-06-12T10:56:09.045967',
                        active: true,
                        nomisLineReference: '1',
                      },
                      consecutiveToSentenceUuid: null,
                      hasRecall: false,
                    },
                    legacyData: {
                      postedDate: '2025-06-12',
                      nomisOutcomeCode: null,
                      outcomeDescription: null,
                      outcomeDispositionCode: null,
                      outcomeConvictionFlag: true,
                    },
                  },
                ],
                overallSentenceLength: null,
                overallConvictionDate: null,
                legacyData: {
                  postedDate: '2025-06-12',
                  nomisOutcomeCode: '1002',
                  outcomeDescription: 'Imprisonment',
                  nextEventDateTime: null,
                  appearanceTime: '10:00:00',
                  outcomeDispositionCode: 'F',
                  outcomeConvictionFlag: true,
                },
              },
              appearances: [
                {
                  appearanceUuid: '8d173286-0c8b-485b-a671-cc02abdb8b79',
                  outcome: {
                    outcomeUuid: '62412083-9892-48c9-bf01-7864af4a8b3c',
                    outcomeName: 'Imprisonment',
                    nomisCode: '1002',
                    outcomeType: 'SENTENCING',
                    displayOrder: 10,
                    relatedChargeOutcomeUuid: 'f17328cf-ceaa-43c2-930a-26cf74480e18',
                    isSubList: false,
                  },
                  courtCode: 'ABDRCT',
                  courtCaseReference: null,
                  appearanceDate: '2023-02-12',
                  warrantId: null,
                  warrantType: 'SENTENCING',
                  nextCourtAppearance: null,
                  charges: [
                    {
                      chargeUuid: 'e6365327-4478-4355-8e1e-aff35c86a554',
                      offenceCode: 'COML017B',
                      offenceStartDate: '2021-08-03',
                      offenceEndDate: null,
                      outcome: {
                        outcomeUuid: 'f17328cf-ceaa-43c2-930a-26cf74480e18',
                        outcomeName: 'Imprisonment',
                        nomisCode: '1002',
                        outcomeType: 'SENTENCING',
                        displayOrder: 10,
                        dispositionCode: 'FINAL',
                      },
                      terrorRelated: null,
                      sentence: {
                        sentenceUuid: 'b1515f6d-b685-46be-b8a7-3f1f87cca976',
                        chargeNumber: null,
                        periodLengths: [
                          {
                            years: 2,
                            months: 11,
                            weeks: null,
                            days: null,
                            periodOrder: 'years,months,weeks,days',
                            periodLengthType: 'SENTENCE_LENGTH',
                            legacyData: null,
                            periodLengthUuid: 'e7b188ef-066e-40be-b59a-d71f2e109ff9',
                          },
                        ],
                        sentenceServeType: 'CONCURRENT',
                        sentenceType: {
                          sentenceTypeUuid: '02fe3513-40a6-47e9-a72d-9dafdd936a0e',
                          description: 'SDS (Standard Determinate Sentence)',
                          classification: 'STANDARD',
                          hintText: null,
                          displayOrder: 10,
                        },
                        convictionDate: null,
                        fineAmount: null,
                        legacyData: {
                          sentenceCalcType: null,
                          sentenceCategory: null,
                          sentenceTypeDesc: null,
                          postedDate: '2025-06-12T10:56:09.045967',
                          active: true,
                          nomisLineReference: '1',
                        },
                        consecutiveToSentenceUuid: null,
                        hasRecall: false,
                      },
                      legacyData: {
                        postedDate: '2025-06-12',
                        nomisOutcomeCode: null,
                        outcomeDescription: null,
                        outcomeDispositionCode: null,
                        outcomeConvictionFlag: true,
                      },
                    },
                  ],
                  overallSentenceLength: null,
                  overallConvictionDate: null,
                  legacyData: {
                    postedDate: '2025-06-12',
                    nomisOutcomeCode: '1002',
                    outcomeDescription: 'Imprisonment',
                    nextEventDateTime: null,
                    appearanceTime: '10:00:00',
                    outcomeDispositionCode: 'F',
                    outcomeConvictionFlag: true,
                  },
                },
              ],
              legacyData: null,
            },
          ],
          pageable: {
            pageNumber: 0,
            pageSize: 20,
            sort: {
              empty: false,
              sorted: true,
              unsorted: false,
            },
            offset: 0,
            paged: true,
            unpaged: false,
          },
          last: true,
          totalElements: 2,
          totalPages: 1,
          size: 20,
          number: 0,
          sort: {
            empty: false,
            sorted: true,
            unsorted: false,
          },
          first: true,
          numberOfElements: 2,
          empty: false,
        },
      },
    })
  },
  stubRecallPerson: (): SuperAgentRequest => {
    return stubFor({
      request: {
        method: 'GET',
        urlPath: '/remand-and-sentencing-api/recall/person/A1234AB',
      },
      response: {
        status: 200,
        headers: { 'Content-Type': 'application/json;charset=UTF-8' },

        jsonBody: [
          {
            recallUuid: 'ABC',
            prisonerId: 'A1234AB',
            revocationDate: '2018-03-03T00:00:00.000Z',
            returnToCustodyDate: null,
            recallType: {
              code: 'LR',
              description: 'Standard',
              fixedTerm: false,
            },
            courtCaseIds: [],
          },
        ],
      },
    })
  },
  stubRecallRecorded: (): SuperAgentRequest => {
    return stubFor({
      request: {
        method: 'POST',
        urlPath: '/remand-and-sentencing-api/recall',
      },
      response: {
        status: 200,
        headers: { 'Content-Type': 'application/json;charset=UTF-8' },
        jsonBody: {
          recallUuid: 'ABC',
        },
      },
    })
  },
}
