---
# Per environment values which override defaults in hmpps-record-a-recall/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: record-a-recall-preprod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://record-a-recall-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    PRISON_API_URL: "https://prison-api-preprod.prison.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-search-preprod.prison.service.justice.gov.uk"
    CALCULATE_RELEASE_DATES_API_URL: "https://calculate-release-dates-api-preprod.hmpps.service.justice.gov.uk"
    REMAND_AND_SENTENCING_API_URL: "https://remand-and-sentencing-api-preprod.hmpps.service.justice.gov.uk"
    ENVIRONMENT_NAME: PRE-PRODUCTION
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: legacy-replacement-alerts-non-prod
