---
# Per environment values which override defaults in hmpps-record-a-recall/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: record-a-recall-preprod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://record-a-recall-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_URL: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
    MANAGE_OFFENCES_API_URL: "https://manage-offences-api-preprod.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    PRISON_API_URL: "https://prison-api-preprod.prison.service.justice.gov.uk"
    ADJUSTMENTS_API_URL: "https://adjustments-api-preprod.hmpps.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-search-preprod.prison.service.justice.gov.uk"
    CALCULATE_RELEASE_DATES_API_URL: "https://calculate-release-dates-api-preprod.hmpps.service.justice.gov.uk"
    REMAND_AND_SENTENCING_API_URL: "https://remand-and-sentencing-api-preprod.hmpps.service.justice.gov.uk"
    COMPONENT_API_URL: "https://frontend-components-preprod.hmpps.service.justice.gov.uk"
    COURT_REGISTER_API_URL: "https://court-register-api-preprod.hmpps.service.justice.gov.uk"
    PRISON_REGISTER_API_URL: "https://prison-register-preprod.hmpps.service.justice.gov.uk"

    DIGITAL_PRISON_SERVICES_URL: "https://digital-preprod.prison.service.justice.gov.uk"
    ADJUSTMENTS_URL: "https://adjust-release-dates-preprod.hmpps.service.justice.gov.uk"
    CRDS_URL: "https://calculate-release-dates-preprod.hmpps.service.justice.gov.uk"
    CCARDS_URL: "https://court-cases-release-dates-preprod.hmpps.service.justice.gov.uk"
    COURT_CASES_RELEASE_DATES_API_URL: "https://court-cases-release-dates-api-preprod.hmpps.service.justice.gov.uk"
    NOMIS_MAPPING_SERVICE_URL: "https://nomis-sync-prisoner-mapping-preprod.hmpps.service.justice.gov.uk"

    ENVIRONMENT_NAME: PRE-PRODUCTION
    AUDIT_ENABLED: "false"

  allowlist:
    ark-dom1-farnborough: 194.33.192.0/24
    ark-dom1-corsham: 194.33.196.0/24
    cymulate-1: 54.217.50.18/32
    cymulate-2: 52.208.202.111/32
    cymulate-3: 52.49.144.209/32
    penetration-test-ip-1: 54.37.241.156/30
    penetration-test-ip-2: 167.71.136.237/32
    groups:
      - circleci
      - internal
      - prisons
      - private_prisons

generic-prometheus-alerts:
  alertSeverity: legacy-replacement-alerts-non-prod
